## Import the basic package

In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler


In [3]:
## Load Data and analysis

In [5]:
dataset=pd.read_csv(f"~/Machine_Learning_Projects/Machine Learning for Diabetes  Data Analysis:  Prediction Diabetes with Python/diabetes.csv")

In [7]:
dataset.shape

(768, 9)

In [9]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [13]:
dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [15]:
dataset.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

## data preprocessing 

In [18]:
X=dataset.drop(columns="Outcome",axis=1)
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

##### Normalization (Standard Scale)

In [21]:
StandardScaleObject=StandardScaler()

In [23]:
StandardScaleObject.fit(X)

StandardScaler()

In [27]:
X=StandardScaleObject.transform(X)
Y=dataset['Outcome']
X,Y

(array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
          0.46849198,  1.4259954 ],
        [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
         -0.36506078, -0.19067191],
        [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
          0.60439732, -0.10558415],
        ...,
        [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
         -0.68519336, -0.27575966],
        [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
         -0.37110101,  1.17073215],
        [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
         -0.47378505, -0.87137393]]),
 0      1
 1      0
 2      1
 3      0
 4      1
       ..
 763    0
 764    0
 765    0
 766    1
 767    0
 Name: Outcome, Length: 768, dtype: int64)

## Splitting the Dataset (Train and Test ) , (X and Y)

In [52]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)
X_train,Y_train,X_test,Y_test

(array([[-0.84488505, -0.96691063, -0.36733675, ..., -0.6082704 ,
          0.3265464 , -0.78628618],
        [ 0.3429808 ,  0.1597866 ,  0.45982725, ..., -0.30366421,
         -0.09929033,  0.57511787],
        [-0.54791859, -0.49745345, -0.57412775, ...,  0.36900779,
         -0.74559573, -0.70119842],
        ...,
        [-0.84488505, -0.74783062,  0.04624525, ...,  0.77514938,
         -0.76673656, -0.27575966],
        [ 1.82781311, -0.30967058,  0.04624525, ..., -0.57019463,
         -0.9992857 ,  0.57511787],
        [ 0.04601433,  0.72313521, -0.57412775, ..., -0.31635613,
         -0.55834837,  0.31985461]]),
 353    0
 711    0
 373    0
 46     0
 682    0
       ..
 451    1
 113    0
 556    0
 667    1
 107    0
 Name: Outcome, Length: 614, dtype: int64,
 array([[ 0.93691372,  1.19259239, -0.26394125, ..., -0.58288655,
         -0.53720754,  0.57511787],
        [ 1.82781311, -1.65544783,  1.90736425, ...,  0.44515934,
         -0.56438861,  1.17073215],
        [-0.5479

In [54]:
X_train.shape,Y_train.shape,"Test",X_test.shape,Y_test.shape

((614, 8), (614,), 'Test', (154, 8), (154,))

## Train model

In [57]:
Model_SVM_Classifier=svm.SVC(kernel='linear') #Support Vector Classifier

In [59]:
Model_SVM_Classifier.fit(X_train,Y_train)

SVC(kernel='linear')

### Evaluation

In [68]:
Y_hat_train=Model_SVM_Classifier.predict(X_train)
print(Y_hat_train)
traning_data_accuracy=accuracy_score(Y_train,Y_hat_train)
print(f" Accuaracy of model in training data is :{traning_data_accuracy}%")

[0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1
 0 1 1 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0
 1 0 0 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 0 1
 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 0 0 1
 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1
 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0
 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0
 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0
 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 

In [70]:
Y_hat_test=Model_SVM_Classifier.predict(X_test)
print(Y_hat_test)
test_data_accuracy=accuracy_score(Y_test,Y_hat_test)
print(f" Accuaracy of model in test data is :{test_data_accuracy}%")

[1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 1 0 1
 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 1 0]
 Accuaracy of model in test data is :0.7207792207792207%


# simulate Real Operation 'Run'

In [85]:
input_data=(7,100,0,0,0,30,0.484,32)

handleInput=np.asarray(input_data).reshape(1,-1)

#must be StandardScaleObject.fit(X) as the data train
NormalizeInput=StandardScaleObject.transform(handleInput)

predicted=Model_SVM_Classifier.predict(NormalizeInput)

print(NormalizeInput,predicted)

if predicted[0]==0:
    print(f"the person not have diabete")
else:
    print(f"the person have diabete")


[[ 0.93691372 -0.65393918 -3.57259724 -1.28821221 -0.69289057 -0.25289651
   0.03661501 -0.10558415]] [0]
the person not have diabete


/home/me/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
